# Generated by Django 4.1 on 2022-08-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='images',
        ),
    ]
