# Generated by Django 4.1 on 2022-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная фотография места'),
        ),
    ]
