# Generated by Django 4.1 on 2022-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='places/', verbose_name='Картинки места'),
        ),
    ]
