# Generated by Django 4.1 on 2022-08-29 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90, message='Широта не может быть меньше -90°'), django.core.validators.MaxValueValidator(90, message='Широта не может быть больше 90°')], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180, message='Долгота не может быть меньше -180°'), django.core.validators.MaxValueValidator(180, message='Долгота не может быть больше 180°')], verbose_name='Долгота'),
        ),
    ]
